drop table booking if exists
drop table member if exists
drop table room if exists
drop table roomtype if exists
create table room(roomcode INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(20),type INTEGER,howmany INTEGER,howmuch INTEGER)
create table roomtype(typecode INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(20))
CREATE TABLE member (name VARCHAR(30) NOT NULL,loginid VARCHAR(20) PRIMARY KEY,passcode VARCHAR(12) NOT NULL)
CREATE TABLE booking (bookcode INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,roomcode INTEGER,person INTEGER,checkin CHAR(10),checkout CHAR(10),name VARCHAR(20),mobile VARCHAR(20))
insert into roomtype values(1,'Suite Room')
insert into roomtype values(2,'Family Room')
insert into roomtype values(3,'Double Room')
insert into roomtype values(4,'Single Room')
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
insert into room values(1,'백두산',1,8,500000)
INSERT INTO member VALUES('user01', 'user01', 'user1234')
insert into booking values(1,6,2,'2021-08-27','2021-08-29','장효원','01099500240')